name: Deploy CodeArtifactProxy
on: 
  workflow_dispatch:
    inputs:
      url:
        description: "First part of the URL"
        required: true
        default: ""
      target_host:
        description: "Set TARGET_HOST OS Env."
        required: true
        default: ""
      aliased:
        description: "Set ALIASED OS Env."
        required: true
        default: ""
      deploy:
        description: "Deployed - true | false"
        required: true
        default: "false"
        type: choice
        options:
        - true
        - false

jobs:
  deploy:
    runs-on: 
      - self-hosted
      - Linux
      - X64
      - eks-dev
      - deploy
    environment: dev
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: master
          repository: InteropIO/basehelmchart
          path: 'helm'
          sparse-checkout: '*'
          sparse-checkout-cone-mode: false
      - uses: mamezou-tech/setup-helmfile@v1.3.0
      - name: Deploy
        run: |
          export PROJECT_NAME=${{ github.event.repository.name }}
          export NAMESPACE=${{ github.event.inputs.namespace }}
          export ALB_INSTANCES=${{ vars.ALB_INSTANCES }}
          export CI_REGISTRY=${{ vars.CI_REGISTRY }}
          export CERT_ARN=${{ vars.CERT_ARN }}
          export IMAGE_TAG=${{ steps.short-sha.outputs.sha }}
          export INSTALLED=${{ github.event.inputs.deploy }}
          export TARGET_HOST=${{ github.event.inputs.target_host }}
          export ALIASED=${{ github.event.inputs.aliased }}
          export URL=${{ github.event.inputs.url }}
          helmfile -f helmfile.yaml apply